	# production Docker container:
# assumes that the ELF has been already built and is available on the baremetal filesystem
# under the bin/ folder. All its required shared libraries should be available as well under bin/

FROM registry.fedoraproject.org/fedora-minimal:30
COPY output/ /
EXPOSE 8080
CMD [ "/project/build/mytest" ]
