#
# Base builder image:
# defines which toolchain will be used to build the C++ code
#
FROM fedora:28 as fmontorsi_builder

RUN yum install -y git make automake gcc gcc-c++ kernel-devel gdb \
                   pax-utils

RUN gcc --version
RUN gdb --version
