version: '3'
services:
  mytest:
    image: "f18m/my-docker-test:1.4" 
    container_name: mytest
    ports:
      - "8080:8080"
    cap_add:
    - SYS_PTRACE
    volumes:
    - /tmp/mytest_coredumps_volume:/cores
    - /tmp/mytest_log_volume:/logs
    ulimits:
      core: -1
#uncomment next line to run valgrind (logs created in /tmp/mytest_log_volume)
#    entrypoint: ["/usr/bin/valgrind", "--log-file=/logs/valgrind.log", "/project/build/mytest"]

 
